"""Generate test files for data pipeline."""
import os

# Build test_bar_builder.py content
lines = []
lines.append('"""Tests for the bar aggregation engine (BarBuilder).')
lines.append('')
lines.append('Covers 1m/5m/15m/60m bar construction from synthetic ticks, gap')
lines.append('tolerance, and EventBus publishing behaviour.')
lines.append('"""')
lines.append('')
lines.append('import asyncio')
lines.append('from datetime import datetime, timedelta, timezone')
lines.append('')
lines.append('import pytest')
lines.append('')
lines.append('from shettyxtreme.core.data_models import Bar, Tick')
lines.append('from shettyxtreme.core.event_bus import Event, EventBus, Topic')
lines.append('from shettyxtreme.data.pipeline.bar_builder import (')
lines.append('    BarBuilder,')
lines.append('    BarBuilderState,')
lines.append('    floor_timestamp,')
lines.append(')')
lines.append('')
lines.append('')
lines.append('# ---------------------------------------------------------------------------')
lines.append('# Helpers')
lines.append('# ---------------------------------------------------------------------------')
lines.append('')
lines.append('')
lines.append('def _make_tick(')
lines.append('    symbol: str = "11536",')
lines.append('    ltp: float = 100.0,')
lines.append('    volume: int = 10,')
lines.append('    timestamp: datetime | None = None,')
lines.append('    exchange: str = "NSE",')
lines.append(') -> Tick:')
lines.append('    if timestamp is None:')
lines.append('        timestamp = datetime.now(timezone.utc)')
lines.append('    return Tick(')
lines.append('        symbol=symbol, exchange=exchange, ltp=ltp, volume=volume,')
lines.append('        timestamp=timestamp,')
lines.append('    )')
lines.append('')
lines.append('')
lines.append('def _make_event(tick: Tick) -> Event:')
lines.append('    return Event(topic=Topic.MARKET_DATA_TICK, data=tick, source="test")')

with open('tests/data/test_bar_builder.py', 'w') as f:
    f.write('\n'.join(lines))
    f.write('\n')

print('test_bar_builder.py header written')
