from typing import Protocol, runtime_checkable

# F-CORE-001: Position/Holding/OrderBook are canonical in core.data_models;
# this module re-exports the same classes so the AccountInfo protocol and
# its consumers share one identity.
from shettyxtreme.core.data_models import Holding, OrderBook, Position


@runtime_checkable
class AccountInfo(Protocol):
    async def get_positions(self) -> list[Position]: ...
    async def get_holdings(self) -> list[Holding]: ...
    async def get_order_book(self) -> list[OrderBook]: ...
    async def get_trade_book(self) -> list: ...
    async def get_margin(self) -> dict: ...
